### PR TITLE
client: use `System.nanoTime()` for a more precise time measurement

### PR DESCRIPTION
**Pull request by lzaoral**

### CODE REVIEW

**Comment by lzaoral** [comment]
@ph4r05 A friendly bump.

**Comment by ph4r05** [comment]
Thanks!

**Comment by lzaoral** [comment]
@ph4r05, do you have any plans for a new release in near future? My ongoing rewrite of [OpenCryptoProject/JCProfiler](https://github.com/OpenCryptoProject/JCProfiler) depends on this PR and I'd love to use the version from MavenCentral instead so that users don't have build this project from sources as well.  It's also the main reason why that project is still being kept as private at the moment. Thank you!

**Comment by ph4r05** [comment]
OK sure, I can release it

**Comment by ph4r05** [comment]
@lzaoral I've pushed 1.0.5 to maven repo. It may take a while until it is propagated.

**Comment by lzaoral** [comment]
Thank you, @ph4r05!  I really appreciate it!

**Pull request merged**
